image: node:22

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - web
    - front
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - out/
    expire_in: 1 week

deploy:
  stage: deploy
  tags:
    - web
    - front
  script:
    - rsync -avz --delete out/ ubuntu:/var/www/pplale.pgw.jp/
  only:
    - main 