stages:
  - setup
  - build
  - test
  - deploy

variables:
  NODE_VERSION: "22"
  NPM_VERSION: "latest"
  # GitHub Pages用の環境変数
  GITHUB_PAGES: "false"

setup:
  stage: setup
  tags:
    - web
  before_script:
    - sleep 5  # Runnerの完全な起動を待つ
  script:
    - |
      echo "Node.js version: "
      node -v
      echo "NPM version: "
      npm -v
      echo "NPM config list: "
      npm config list
      echo "NPM cache verify: "
      npm cache verify
  allow_failure: false

build:
  stage: build
  tags:
    - web
  before_script:
    - sleep 2
  script:
    - |
      echo "Starting build process..."
      echo "Installing dependencies..."
      npm ci
      echo "Building application..."
      npm run build
      echo "Build completed. Checking output directory..."
      ls -la .next/
  artifacts:
    paths:
      - .next/
      - public/
    expire_in: 1 week
  allow_failure: false

test:
  stage: test
  tags:
    - web
  before_script:
    - sleep 2
  script:
    - |
      echo "Starting tests..."
      echo "Checking build output..."
      ls -la .next/
      echo "Verifying file permissions..."
      find .next/ -type f -exec ls -l {} \;
  dependencies:
    - build
  allow_failure: false

deploy:
  stage: deploy
  tags:
    - web
  before_script:
    - sleep 2
    - |
      mkdir -p ~/.ssh
      echo "$SSH_PRIVATE_KEY" > ~/.ssh/ubuntu
      chmod 600 ~/.ssh/ubuntu
      cat >> ~/.ssh/config << EOF
      Host ubuntu
        User yokan
        HostName 192.168.0.5
        IdentityFile ~/.ssh/ubuntu
        StrictHostKeyChecking no
      EOF
      chmod 600 ~/.ssh/config
  script:
    - |
      echo "Starting deployment..."
      echo "Checking source files..."
      ls -la .next/
      echo "Deploying to server..."
      # standaloneモード用のデプロイ
      rsync -avz --delete --progress .next/standalone/* ubuntu:/var/www/pplale.pgw.jp/
      rsync -avz --delete --progress .next/static ubuntu:/var/www/pplale.pgw.jp/.next/
      rsync -avz --delete --progress public/ ubuntu:/var/www/pplale.pgw.jp/public/
      echo "Setting permissions..."
      ssh ubuntu "chown -R yokan:yokan /var/www/pplale.pgw.jp && chmod -R 755 /var/www/pplale.pgw.jp"
      echo "Restarting Next.js server..."
      ssh ubuntu "sudo systemctl restart pplale"
      echo "Restarting Nginx..."
      ssh ubuntu "sudo systemctl restart nginx"
      echo "Verifying deployment..."
      ssh ubuntu "ls -la /var/www/pplale.pgw.jp/"
  environment:
    name: production
    url: https://pplale.pgw.jp
  only:
    - main
  allow_failure: false 