stages:
  - setup
  - build

variables:
  DOCKER_IMAGE: "pplale-web"
  DOCKER_TAG: "latest"
  # GitHub Pages用の環境変数
  GITHUB_PAGES: "false"
  # Firebase環境変数
  FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
  FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
  FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}

setup:
  stage: setup
  tags:
    - web
  before_script:
    - sleep 3
  script:
    - |
      echo "Docker version: "
      docker --version
  allow_failure: false

build:
  stage: build
  tags:
    - web
  before_script:
    - sleep 2
  script:
    - |
      echo "Building Docker image..."
      docker build --no-cache -t $DOCKER_IMAGE:$DOCKER_TAG .
      echo "Deploying..."
      docker stop pplale-web || true
      docker rm pplale-web || true
      docker run -d \
        --name pplale-web \
        --restart always \
        -p 3000:3000 \
        -e FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID \
        -e FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL \
        -e FIREBASE_PRIVATE_KEY="$FIREBASE_PRIVATE_KEY" \
        $DOCKER_IMAGE:$DOCKER_TAG
      echo "Restarting Nginx..."
      sudo systemctl restart nginx
      echo "Verifying deployment..."
      docker ps | grep pplale-web
  environment:
    name: production
    url: https://pplale.pgw.jp
  only:
    - main
  allow_failure: false 