stages:
  - setup
  - build

variables:
  NODE_VERSION: "22"
  NPM_VERSION: "latest"
  DOCKER_IMAGE: "pplale-web"
  DOCKER_TAG: "latest"
  # GitHub Pages用の環境変数
  GITHUB_PAGES: "false"

setup:
  stage: setup
  tags:
    - web
  before_script:
    - sleep 5
  script:
    - |
      echo "Node.js version: "
      node -v
      echo "NPM version: "
      npm -v
      echo "Docker version: "
      docker --version
  allow_failure: false

build:
  stage: build
  tags:
    - web
  before_script:
    - sleep 2
  script:
    - |
      echo "Building Docker image..."
      docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
      echo "Deploying..."
      docker stop pplale-web || true
      docker rm pplale-web || true
      docker run -d \
        --name pplale-web \
        --restart always \
        -p 3000:3000 \
        -v /var/www/pplale.pgw.jp/static:/app/static \
        -v /var/www/pplale.pgw.jp/public:/app/public \
        $DOCKER_IMAGE:$DOCKER_TAG
      echo "Restarting Nginx..."
      sudo systemctl restart nginx
      echo "Verifying deployment..."
      docker ps | grep pplale-web
  environment:
    name: production
    url: https://pplale.pgw.jp
  only:
    - main
  allow_failure: false 