FROM node:22-alpine

WORKDIR /app

# 依存関係のインストール
COPY package*.json ./
RUN npm install

# ソースコードのコピー
COPY . .

# 開発環境の設定
ENV NODE_ENV=development
ENV PORT=3000

# アプリケーションの起動
CMD ["npm", "run", "dev"] 